In [1]:
import numpy as np
a = np.arange(11)**2

In [2]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [3]:
a[2]

4

In [4]:
a[-2]

81

In [5]:
a[2:7]

array([ 4,  9, 16, 25, 36])

In [6]:
a[2:-2]

array([ 4,  9, 16, 25, 36, 49, 64])

In [7]:
a[:7]

array([ 0,  1,  4,  9, 16, 25, 36])

In [8]:
a[:11:2]

array([  0,   4,  16,  36,  64, 100])

In [9]:
a[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0])

In [12]:
students = np.array([['Alice','Beth','Cathy','Dorothy'],[65,78,90,81],[71,82,79,92]])

In [13]:
students

array([['Alice', 'Beth', 'Cathy', 'Dorothy'],
       ['65', '78', '90', '81'],
       ['71', '82', '79', '92']], dtype='<U7')

In [14]:
students[0][2]

'Cathy'

In [16]:
students[0]

array(['Alice', 'Beth', 'Cathy', 'Dorothy'], dtype='<U7')

In [17]:
students[1]

array(['65', '78', '90', '81'], dtype='<U7')

In [18]:
students[2]

array(['71', '82', '79', '92'], dtype='<U7')

In [21]:
students[1,2]

'90'

In [22]:
students[0:2,2:4]

array([['Cathy', 'Dorothy'],
       ['90', '81']], dtype='<U7')

In [23]:
students[:,1:2]

array([['Beth'],
       ['78'],
       ['82']], dtype='<U7')

In [24]:
students[:,1:3]

array([['Beth', 'Cathy'],
       ['78', '90'],
       ['82', '79']], dtype='<U7')

In [25]:
students[-1,:]

array(['71', '82', '79', '92'], dtype='<U7')

In [26]:
students[-3:-1,-2:]

array([['Cathy', 'Dorothy'],
       ['90', '81']], dtype='<U7')

In [27]:
students[0,...]

array(['Alice', 'Beth', 'Cathy', 'Dorothy'], dtype='<U7')

In [28]:
students[...,1]

array(['Beth', '78', '82'], dtype='<U7')