In [3]:
!pip install numpy  --upgrade

Requirement already up-to-date: numpy in /Users/emisaelcalderonclemente/miniconda3/lib/python3.5/site-packages (1.16.4)


In [4]:
import numpy as np

In [9]:
array_one = np.array([1,2,3,4])


In [10]:
array_one

array([1, 2, 3, 4])

In [13]:
numbers = [9,8,7,6]
array_two = np.array(numbers)
array_two

array([9, 8, 7, 6])

In [14]:
array_of_zeroes = np.zeros((3,4))
array_of_zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
array_of_onees = np.ones((3,4),dtype=np.int16)
array_of_onees

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [25]:
array_of_empty = np.empty((2,3))
array_of_empty

array([[2.31584178e+077, 1.73060648e-077, 2.23975853e-314],
       [2.31109257e-314, 2.31584178e+077, 4.21546248e-309]])

In [27]:
array_eye = np.eye((5))
array_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
array_2d = np.array([(2,4,6),(3,5,7)])
array_2d


array([[2, 4, 6],
       [3, 5, 7]])

In [32]:
array_2d.shape

(2, 3)

In [34]:
array_nd = np.arange(6).reshape(3,2)
array_nd


array([[0, 1],
       [2, 3],
       [4, 5]])

In [35]:
array_ones = np.ones_like(array_nd)
array_ones

array([[1, 1],
       [1, 1],
       [1, 1]])