In [1]:
import numpy as np

In [2]:
angles = np.array([0,30,45,60,90])

In [3]:
print(angles)

[ 0 30 45 60 90]


In [4]:
angles_radians = angles * np.pi/180
angles_radians

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [5]:
print('Sine of angles in the array:')
print(np.sin(angles_radians))

Sine of angles in the array:
[0.         0.5        0.70710678 0.8660254  1.        ]


In [7]:
angles_radians = np.radians(angles)
angles_radians

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [9]:
print('Cosine of angles in the array:')
print(np.cos(angles_radians))

Cosine of angles in the array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [10]:
print('Tangent of angles in the array:')
print(np.tan(angles_radians))

Tangent of angles in the array:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [11]:
sin = np.sin(angles * np.pi/180)
print('Compute sine inverse of angles. Returned values are in radians.')
inv = np.arcsin(sin)
print(sin)

Compute sine inverse of angles. Returned values are in radians.
[0.         0.5        0.70710678 0.8660254  1.        ]


In [12]:
print('Check the result by converting to degrees:')
print(np.degrees(inv))

Check the result by converting to degrees:
[ 0. 30. 45. 60. 90.]


In [17]:
test_scores = np.array([33.32,56.98,21.52,44.32,55.63,13.75,43.47,43.34])
print('Mean test scores of the students: ')
print(np.mean(test_scores))

Mean test scores of the students: 
39.04125


In [16]:
print('Mean test scores of the students: ')
print(np.median(test_scores))

Mean test scores of the students: 
43.405
