In [1]:
import numpy as np


In [3]:
a = np.arange(6)

In [4]:
a

array([0, 1, 2, 3, 4, 5])

In [5]:
print(a)

[0 1 2 3 4 5]


In [7]:
b = np.arange(6).reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [9]:
c = np.arange(24).reshape(2,3,4)

In [10]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [13]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [18]:
np.set_printoptions(threshold = 10)

In [19]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]
