In [2]:
import numpy as np
a = np.arange(11)**2

In [3]:
a


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [4]:
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [5]:
students = np.array([['Alice','Beth','Cathy','Dorothy'],[65,78,90,81],[71,82,79,92]])
for i in students:
    print('i= ',i)

i=  ['Alice' 'Beth' 'Cathy' 'Dorothy']
i=  ['65' '78' '90' '81']
i=  ['71' '82' '79' '92']


In [8]:
for element in students.flatten(order='F'):
    print(element)

Alice
65
71
Beth
78
82
Cathy
90
79
Dorothy
81
92


In [12]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
for i in np.nditer(x):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [14]:
for i in np.nditer(x,order='F'):
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


In [16]:
for i in np.nditer(x,order='F',flags=['external_loop']):
    print(i)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [18]:
for arr in np.nditer(x,op_flags=['readwrite']):
    arr[...] = arr * arr

In [19]:
x

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [21]:
a  = np.array([("Germany","France","Hungary","Austria"),("Berlin","Paris","Budapest","Vienna")])
a

array([['Germany', 'France', 'Hungary', 'Austria'],
       ['Berlin', 'Paris', 'Budapest', 'Vienna']], dtype='<U8')

In [22]:
a.shape

(2, 4)

In [23]:
a.ravel()

array(['Germany', 'France', 'Hungary', 'Austria', 'Berlin', 'Paris',
       'Budapest', 'Vienna'], dtype='<U8')

In [24]:
a.T

array([['Germany', 'Berlin'],
       ['France', 'Paris'],
       ['Hungary', 'Budapest'],
       ['Austria', 'Vienna']], dtype='<U8')

In [25]:
a.T.ravel()

array(['Germany', 'Berlin', 'France', 'Paris', 'Hungary', 'Budapest',
       'Austria', 'Vienna'], dtype='<U8')

In [27]:
a.reshape(4,2)

array([['Germany', 'France'],
       ['Hungary', 'Austria'],
       ['Berlin', 'Paris'],
       ['Budapest', 'Vienna']], dtype='<U8')

In [28]:
a.shape

(2, 4)

In [29]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
np.arange(15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [31]:
np.arange(15).reshape(3,6)

ValueError: cannot reshape array of size 15 into shape (3,6)

In [35]:
countries  = np.array(["Germany","France","Hungary","Austria","Berlin","Paris"])
countries

array(['Germany', 'France', 'Hungary', 'Austria', 'Berlin', 'Paris'],
      dtype='<U7')

In [37]:
countries.reshape(3,-1)

array([['Germany', 'France'],
       ['Hungary', 'Austria'],
       ['Berlin', 'Paris']], dtype='<U7')

In [36]:
countries.reshape(-1,3)

array([['Germany', 'France', 'Hungary'],
       ['Austria', 'Berlin', 'Paris']], dtype='<U7')